Repository Apply-Creatures/creature-shoveler, pull requests merged in 2024-07, with the labels that each got.

#1 🚀 use of bun instead of npm/node and pre-push kick of the CI
  .husky/pre-commit
  .husky/pre-push
  .woodpecker/.ci.yaml
  README.md
  bun.lockb
  package-lock.json
  package.json
Labels: enhancement

#3 📃 CI badge to README
  README.md
Labels: documentation

#4 🔨 Fix for async call without await
  src/index.ts
Labels: bug

#2 🔨 Fix multi-selector enquirer
  templates/node.js/.editorconfig.ejs
  templates/node.js/.gitignore.ejs
  templates/node.js/.nvmrc.ejs
  templates/node.js/CODE_OF_CONDUCT.ejs.md
  templates/node.js/CONTRIBUTING.ejs.md
  templates/node.js/Dockerfile.ejs
  templates/node.js/LICENSE.ejs
  templates/node.js/SECURITY.ejs.md
  templates/node.js/package.ejs.json
  templates/node.js/tsconfig.ejs.json
Labels: bug

#5 📃 floss badge
  README.md
Labels: documentation

#8 👾 floss related files
  templates/CODE_OF_CONDUCT.ejs.md
  templates/CONTRIBUTING.ejs.md
  templates/LICENSE.ejs.txt
  templates/SECURITY.ejs.md
Labels: enhancement

#7 👾 python templates, uv, ruff configs, dockerfile, ignores
  templates/CODE_OF_CONDUCT.ejs.md
  templates/CONTRIBUTING.ejs.md
  templates/LICENSE.ejs.txt
  templates/SECURITY.ejs.md
  templates/python/.dockerignore.ejs
  templates/python/.gitignore.ejs
  templates/python/Dockerfile.ejs
  templates/python/ruff.ejs.toml
  templates/python/uv.config.ejs.toml
Labels: enhancement

#6 👾 Rust templates, cargo file, dockerfile, ignores
  templates/CODE_OF_CONDUCT.ejs.md
  templates/CONTRIBUTING.ejs.md
  templates/LICENSE.ejs.txt
  templates/SECURITY.ejs.md
  templates/python/.dockerignore.ejs
  templates/python/.gitignore.ejs
  templates/python/Dockerfile.ejs
  templates/python/ruff.ejs.toml
  templates/python/uv.config.ejs.toml
  templates/rust/.dockerignore.ejs
  templates/rust/.gitignore.ejs
  templates/rust/Cargo.ejs.toml
  templates/rust/Dockerfile.ejs
Labels: enhancement
